on:
  push:
    branches: [ main ]

name: build and publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure secrets
      run: |
        echo ${{ secrets.RAILS_MASTER_KEY }} > config/master.key
        AWS_NUMBER="AWS_ACCOUNT_NUMBER=${{secrets.AWS_ACCOUNT_NUMBER}}"
        echo $AWS_NUMBER
        echo $AWS_NUMBER > .env

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: math_power
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: docker-compose deploy
      uses: wshihadeh/docker-deployment-action@master
      with:
        #pre_deployment_command_args: 'bundle exec rake db:migrate' # todo-improve: maybe better than executing in booting step
        remote_docker_host: ${{ secrets.SSH_LOGIN }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        deploy_path: math-docker
        stack_file_name: docker-compose.yml
        pull_images_first: true
        args: --env-file .env up -d
